PSQLADM-131 : Fixup scripts for 8.0
Issue
Scripts are not woring with PXC 8.0

Solution
Many fixes. Mostly due to authentication changes with 8.0
For instance, the password (authentication_string) field can now contain
binary strings (so unprintable characters), so there is a need
to properly escape the strings and to properly iterate over the
return values from queries.

diff --git a/proxysql-admin b/proxysql-admin
--- a/proxysql-admin
+++ b/proxysql-admin
@@ -52,6 +52,10 @@ fi
 readonly    PROXYSQL_ADMIN_VERSION="1.4.13"
 declare  -i DEBUG=0
 
+# default timeout is 10 seconds
+declare  -i TIMEOUT=10
+
+
 #
 # Global variables used by the script
 #
@@ -95,6 +99,8 @@ declare -i USE_EXISTING_MONITOR_PASSWORD=0
 declare -i WITH_CLUSTER_APP_USER=1
 
 declare    WRITER_IS_READER="ondemand"
+declare    MYSQL_CLIENT_VERSION=""
+
 
 #-------------------------------------------------------------------------------
 #
@@ -296,6 +302,7 @@ function check_permission() {
 #
 # Globals:
 #   DEBUG
+#   TIMEOUT
 #
 # Arguments:
 #   1: lineno
@@ -323,6 +330,7 @@ function exec_sql() {
   local more_options=""
   local retvalue
   local retoutput
+  local default_auth=""
 
   if [[ $# -ge 7 ]]; then
     args=$7
@@ -334,9 +342,21 @@ function exec_sql() {
 
   debug "$lineno" "exec_sql : $user@$hostname:$port ==> $query"
 
-  retoutput=$(printf "[client]\nuser=${user//%/%%}\npassword=\"${password//%/%%}\"\nhost=${hostname//%/%%}\nport=${port//%/%%}"  \
-      | mysql --defaults-file=/dev/stdin --protocol=tcp \
-           --unbuffered --batch --silent ${args} -e "${query}")
+  if [[ $MYSQL_CLIENT_VERSION == "8.0" ]]; then
+    default_auth="default-auth=mysql_native_password"
+  fi
+
+  retoutput=$(mysql --defaults-file=/dev/stdin --protocol=tcp \
+           --unbuffered --batch --silent ${args} -e "$query" <<EOF
+[client]
+user=${user//%/%%}
+password="${password//%/%%}"
+host=${hostname//%/%%}
+port=${port//%/%%}
+connect-timeout=${TIMEOUT}
+${default_auth}
+EOF
+)
   retvalue=$?
 
   if [[ $DEBUG -eq 1 ]]; then
@@ -380,7 +400,7 @@ function exec_sql() {
 # Arguments:
 #   1: lineno
 #   2: The SQL query
-#   2: (optional) Additional arguments to the mysql client for the query
+#   3: (optional) Additional arguments to the mysql client for the query
 #   4: (optional) more options, see exec_sql
 #
 function proxysql_exec() {
@@ -762,7 +782,7 @@ function user_input_check() {
       check_cmd $? $LINENO "Failed to query ProxySQL for the user."\
                            "\n-- Please check the ProxySQL connection parameters and status."
 
-      if [[ -z "$precheck_user" ]]; then  
+      if [[ -z "$precheck_user" ]]; then
         mysql_exec "$LINENO" "CREATE USER $username@'$USER_HOST_RANGE' IDENTIFIED BY '$password';"
         check_cmd $? $LINENO "Failed to add the PXC application user to PXC: $username" \
                              "\n-- Please check if '$CLUSTER_USERNAME'@'$CLUSTER_HOSTNAME' has the proper permissions to create the montioring user"
@@ -1360,11 +1380,9 @@ function get_proxysql_users() {
   check_cmd $? $LINENO "Failed to load user list from ProxySQL database."\
                        "\n-- Please check the ProxySQL connection parameters and status."
   proxysql_users=$(echo "$proxysql_users" |
-                      sed 's/\t/,/g' |
-                      egrep -v "username,password" |
                       sort |
                       uniq )
-  printf "$proxysql_users"
+  printf "%s" "$proxysql_users"
 }
 
 
@@ -1438,7 +1456,7 @@ function syncusers() {
     5.6)
       password_field="Password"
       ;;
-    5.7)
+    5.7 | 8.0)
       password_field="authentication_string"
       ;;
     10.2)
@@ -1455,8 +1473,7 @@ function syncusers() {
   esac
   
   mysql_users=$(mysql_exec "$LINENO" "SELECT User,${password_field} FROM mysql.user where ${password_field}!=''" "" "hide_output" |
-                  sed 's/\t/,/g' |
-                  egrep -v "User,${password_field}|mysql.sys|mysql.session" |
+                  egrep -v "mysql.sys|mysql.session|mysql.infoschema" |
                   sort |
                   uniq )
   check_cmd $? $LINENO "Failed to load the user list from PXC."\
@@ -1469,29 +1486,53 @@ function syncusers() {
   echo -e "\nSyncing user accounts from PXC to ProxySQL"
 
   # TEST FOR USERS THAT EXIST IN MYSQL BUT NOT IN PROXYSQL HERE AND ADD
-  for mysql_user in $mysql_users;do
+
+  # Escape all backslashes here, because the read will evaluate
+  # the escaped chars
+  mysql_users=${mysql_users//\\/\\\\}
+  while read line; do
+    if [[ -z $line ]]; then
+      continue
+    fi
+
+    mysql_user=$line
+
     local match=0
-    for proxysql_user in $proxysql_users;do
-      if [ "$proxysql_user" == "$mysql_user" ];then
+    proxysql_users=${proxysql_users//\\/\\\\}
+    while read pline; do
+      if [[ -z $pline ]]; then
+        continue
+      fi
+      if [ "$pline" == "$mysql_user" ];then
         match=1
         break
       fi
-    done
-    if [[ $match -eq 0 ]]; then
-      local user=$(echo $mysql_user | cut -d, -f1)
-      local password=$(echo $mysql_user | cut -d, -f2)
+    done< <(printf "%s\n" "${proxysql_users}")
 
-      # Check if same username exists with a different password, delete the user to recreate.
-      for proxysql_user in $proxysql_users; do
-        echo $proxysql_user | grep "^${user}," > /dev/null
-        if [ "$?" == 0 ];then
-          # Remove the user
+    if [[ $match -eq 0 ]]; then
+      local user=$(echo "$mysql_user" | cut -f1)
+      local password=$(echo "$mysql_user" | cut -f2)
+
+      # escape SQL input
+      # Since we're using single quotes within the SQL statement, only need
+      # to escape the single quotes for SQL
+      password=${password//\'/\'\'}
+
+      # Check if same username exists with a different password
+      # delete the user to recreate.
+      while read pline; do
+        if [[ -z $pline ]]; then
+          continue
+        fi
+        local puser=$(echo "$pline" | cut -f1)
+        if [[ "$puser" == "$user" ]]; then
           echo "Removing existing user from ProxySQL: $user"
           proxysql_exec "$LINENO" "DELETE FROM mysql_users WHERE username='${user}' and default_hostgroup=$WRITE_HOSTGROUP_ID"
           check_cmd $? $LINENO "Failed to delete the user ($user) from ProxySQL database."\
                                "\n-- Please check the ProxySQL connection parameters and status."
+          break
         fi
-      done
+      done< <(printf "%s\n" "${proxysql_users}")
 
       local is_proxysql_admin_user
       is_proxysql_admin_user=$(proxysql_admin_user_check $user)
@@ -1511,30 +1552,40 @@ function syncusers() {
         fi
       fi
     fi
-  done
+  done< <(printf "%s\n" "${mysql_users}")
 
   if [[ $SYNCUSERS -eq 1 ]]; then
     # TEST FOR USERS THAT EXIST IN PROXYSQL BUT NOT IN MYSQL HERE AND REMOVE
     # Again get all users
     proxysql_users=$(get_proxysql_users)
-    for proxysql_user in $proxysql_users; do
+
+    pusers=${proxysql_users//\\/\\\\}
+    while read pline; do
+      if [[ -z $pline ]]; then
+        continue
+      fi
+      proxysql_user=$pline
+
       local match=0
-      for mysql_user in $mysql_users;do
-        if [ "$proxysql_user" == "$mysql_user" ];then
+      while read line; do
+        if [[ -z $line ]]; then
+          continue
+        fi
+        if [ "$proxysql_user" == "$line" ];then
           match=1
           break
         fi
-      done
+      done< <(printf "%s\n", "$mysql_users")
 
-      if [ "$match" == 0 ];then
+      if [ "$match" -eq 0 ];then
         # Delete the ProxySQL user
-        user=$(echo $proxysql_user | cut -d, -f1)
-        echo -e "\nRemoving user from ProxySQL: $proxysql_user"
+        local user=$(echo "$proxysql_user" | cut -f1)
+        echo -e "\nRemoving user from ProxySQL: $user"
         proxysql_exec "$LINENO" "DELETE FROM mysql_users WHERE username='${user}' and default_hostgroup=$WRITE_HOSTGROUP_ID"
         check_cmd $? $LINENO "Failed to delete the user ($user) from ProxySQL database."\
                              "\n-- Please check the ProxySQL connection parameters and status."
       fi
-    done
+    done< <(printf "%s\n" "$proxysql_users")
   fi
   proxysql_load_to_runtime_save_to_disk "MYSQL USERS" $LINENO
 }
@@ -1848,11 +1899,6 @@ function parse_args() {
     esac
   fi
 
-  if [[ ! -e $(which mysql 2> /dev/null) ]] ;then
-    error $LINENO "The mysql client was not found, please install the mysql client package."
-    exit 1
-  fi
-
   # Check the options gathered from the command line
   if [[ $QUICK_DEMO -eq 0 ]]; then
     if [[ -z "$PROXYSQL_USERNAME" ]];then
@@ -2038,6 +2084,44 @@ function main() {
   fi
 }
 
+# Outputs the version string (major.minor) for the path passed in
+#
+# Globals
+#   None
+#
+# Arguments
+#   Parameter 1 : Path to the client
+#
+# Outputs
+#   The version number (major.minor).  The version numbers are
+#   normalized to two digits (to allow for string comparison).
+#   So 5.6 is outputted as "05.06"
+#
+function get_mysql_version()
+{
+
+  local mysql_path=$1
+  local version_string
+  version_string=$(${mysql_path} --version)
+
+  if echo "$version_string" | grep -qe "[[:space:]]5\.5\."; then
+    echo "5.5"
+  elif echo "$version_string" | grep -qe "[[:space:]]5\.6\."; then
+    echo "5.6"
+  elif echo "$version_string" | grep -qe "[[:space:]]5\.7\."; then
+    echo "5.7"
+  elif echo "$version_string" | grep -qe "[[:space:]]8\.0\."; then
+    echo "8.0"
+  elif echo "$version_string" | grep -qe "[[:space:]]10\.2\."; then
+    echo "10.2"
+  elif echo "$version_string" | grep -qe "[[:space:]]10\.3\."; then
+    echo "10.3"
+  else
+    echo "$version_string"
+    return 1
+  fi
+  return 0
+}
 
 #-------------------------------------------------------------------------------
 #
@@ -2050,6 +2134,21 @@ if [ -e "/dummypathnonexisting/.mylogin.cnf" ]; then
   exit 1
 else
   export HOME="/dummypathnonexisting"
+fi
+
+#
+# Check that we can find the mysql client
+#
+if [[ ! -e $(which mysql 2> /dev/null) ]] ;then
+  error $LINENO "The mysql client was not found, please install the mysql client package."
+  exit 1
+fi
+
+MYSQL_CLIENT_VERSION=$(get_mysql_version "mysql")
+if [[ $? -ne 0 ]]; then
+  error $LINENO "Cannot determine the MySQL client version from the version string"
+  echo "-- Version string : $MYSQL_CLIENT_VERSION"
+  exit 1
 fi
 
 parse_args "$@"
diff --git a/proxysql-status b/proxysql-status
--- a/proxysql-status
+++ b/proxysql-status
@@ -24,6 +24,38 @@ Usage example:
 EOF
 }
 
+# Extracts the version from a version string
+#
+# Globals
+#   None
+#
+# Arguments
+#   Parameter 1: the path to the mysqld binary
+#
+# Outputs
+#   Writes a string with the major/minor version numbers
+#   Such as "5.7" or "8.0"
+function get_mysql_version() {
+  local mysqld_path="$1"
+  local mysqld_version=$(${mysqld_path} --version)
+  if echo "$mysqld_version" | grep -qe "[[:space:]]5\.5\."; then
+    echo "5.5"
+  elif echo "$mysqld_version" | grep -qe "[[:space:]]5\.6\."; then
+    echo "5.6"
+  elif echo "$mysqld_version" | grep -qe "[[:space:]]5\.7\."; then
+    echo "5.7"
+  elif echo "$mysqld_version" | grep -qe "[[:space:]]8\.0\."; then
+    echo "8.0"
+  elif echo "$version_string" | grep -qe "[[:space:]]10\.2\."; then
+    echo "10.2"
+  elif echo "$version_string" | grep -qe "[[:space:]]10\.3\."; then
+    echo "10.3"
+  else
+    echo "$mysqld_version"
+    return 1
+  fi
+}
+
 #
 # Executes an SQL query
 #
@@ -42,10 +74,22 @@ function mysql_exec() {
   local query=$2
   local retvalue
   local retoutput
+  local default_auth=""
 
-  retoutput=$(printf "[client]\nuser=${USER}\npassword=\"${PASSWORD}\"\nhost=${HOST}\nport=${PORT}"  \
-      | mysql --defaults-file=/dev/stdin --protocol=tcp \
-            ${args} -e "${query}")
+  if [[ $MYSQL_CLIENT_VERSION == "8.0" ]]; then
+    default_auth="default-auth=mysql_native_password"
+  fi
+
+  retoutput=$(mysql --defaults-file=/dev/stdin --protocol=tcp \
+           ${args} -e "${query}" <<EOF
+[client]
+user=${USER//%/%%}
+password="${PASSWORD//%/%%}"
+host=${HOST//%/%%}
+port=${PORT//%/%%}
+${default_auth}
+EOF
+)
   retvalue=$?
 
   if [[ -n $retoutput ]]; then
@@ -150,10 +194,16 @@ function parse_args() {
 
 
 parse_args "$@"
+MYSQL_CLIENT_VERSION=$(get_mysql_version "mysql")
+if [[ $? -ne 0 ]]; then
+    echo "ERROR: Cannot determine the MySQL client version from the version string"
+    echo "-- Version string : $MYSQL_CLIENT_VERSION"
+    exit 1
+fi
 
 if [[ $DUMP_ALL -eq 1 || $DUMP_MAIN -eq 1 ]]; then
     echo "............ DUMPING MAIN DATABASE ............"
-    TABLES=$(mysql_exec -BN "SHOW TABLES $RUNTIME_OPTION" 2>/dev/null)
+    TABLES=$(mysql_exec -BN "SHOW TABLES $RUNTIME_OPTION")
     for table in $TABLES
     do
         if [[ -n $TABLE_FILTER && $table != *${TABLE_FILTER}* ]]; then
@@ -170,7 +220,7 @@ fi
 
 if [[ $DUMP_ALL -eq 1 || $DUMP_STATS -eq 1 ]]; then
     echo "............ DUMPING STATS DATABASE ............"
-    TABLES=$(mysql_exec -BN "SHOW TABLES FROM stats" 2> /dev/null)
+    TABLES=$(mysql_exec -BN "SHOW TABLES FROM stats")
     for table in $TABLES
     do
         if [[ -n $TABLE_FILTER && $table != *${TABLE_FILTER}* ]]; then
@@ -187,7 +237,7 @@ fi
 
 if [[ $DUMP_ALL -eq 1 || $DUMP_MONITOR -eq 1 ]]; then
     echo "............ DUMPING MONITOR DATABASE ............"
-    TABLES=$(mysql_exec -BN "SHOW TABLES FROM monitor" 2> /dev/null)
+    TABLES=$(mysql_exec -BN "SHOW TABLES FROM monitor")
     for table in $TABLES
     do
         if [[ -n $TABLE_FILTER && $table != *${TABLE_FILTER}* ]]; then
diff --git a/proxysql_node_monitor b/proxysql_node_monitor
--- a/proxysql_node_monitor
+++ b/proxysql_node_monitor
@@ -262,12 +262,24 @@ function exec_sql() {
   local more_options="${10}"
   local retvalue
   local retoutput
+  local default_auth=""
 
   debug "$lineno" "exec_sql : $user@$hostname:$port ==> $query"
 
-  retoutput=$(printf "[client]\n${client_options}\nuser=${user}\npassword=\"${password}\"\nhost=${hostname}\nport=${port}"  \
-      | timeout ${timeout_secs} mysql --defaults-file=/dev/stdin --protocol=tcp \
-              ${args} -e "$query")
+  if [[ $MYSQL_CLIENT_VERSION == "8.0" ]]; then
+    default_auth="default-auth=mysql_native_password"
+  fi
+
+  retoutput=$(timeout ${timeout_secs} mysql --defaults-file=/dev/stdin --protocol=tcp \
+           ${args} -e "${query}" <<EOF
+[client]
+user=${user//%/%%}
+password="${password//%/%%}"
+host=${hostname//%/%%}
+port=${port//%/%%}
+${default_auth}
+EOF
+)
   retvalue=$?
 
   if [[ $DEBUG -eq 1 ]]; then
@@ -989,6 +1001,45 @@ function find_online_cluster_host() {
   return 1
 }
 
+# Outputs the version string (major.minor) for the path passed in
+#
+# Globals
+#   None
+#
+# Arguments
+#   Parameter 1 : Path to the client
+#
+# Outputs
+#   The version number (major.minor).  The version numbers are
+#   normalized to two digits (to allow for string comparison).
+#   So 5.6 is outputted as "05.06"
+#
+function get_mysql_version()
+{
+
+  local mysql_path=$1
+  local version_string
+  version_string=$(${mysql_path} --version)
+
+  if echo "$version_string" | grep -qe "[[:space:]]5\.5\."; then
+    echo "5.5"
+  elif echo "$version_string" | grep -qe "[[:space:]]5\.6\."; then
+    echo "5.6"
+  elif echo "$version_string" | grep -qe "[[:space:]]5\.7\."; then
+    echo "5.7"
+  elif echo "$version_string" | grep -qe "[[:space:]]8\.0\."; then
+    echo "8.0"
+  elif echo "$version_string" | grep -qe "[[:space:]]10\.2\."; then
+    echo "10.2"
+  elif echo "$version_string" | grep -qe "[[:space:]]10\.3\."; then
+    echo "10.3"
+  else
+    echo "$version_string"
+    return 1
+  fi
+  return 0
+}
+
 function main() {
   # Monitoring user needs 'REPLICATION CLIENT' privilege
   log $LINENO "###### Percona XtraDB Cluster status ######"
@@ -1039,6 +1090,13 @@ function main() {
 #
 
 parse_args "$@"
+MYSQL_CLIENT_VERSION=$(get_mysql_version "mysql")
+if [[ $? -ne 0 ]]; then
+  error $LINENO "Cannot determine the MySQL client version from the version string"
+  log "" "-- Version string : $MYSQL_CLIENT_VERSION"
+  exit 1
+fi
+
 debug $LINENO "#### START PROXYSQL NODE MONITOR"
 main
 debug $LINENO "#### END PROXYSQL NODE MONITOR"
